SAVE_GAME_TO_FILE = false
SAVE_FILE = "savefile.txt"
PRINT_BOARD = false
TEAMS = ["blue", "cyan", "green", "yellow"]
WRITE_FEATURES = true
MAX_TURNS = 500

[LogSettings]
LOG_OUTPUT = "stderr"
LOG_LEVEL = "Info"
GAME_LOG_LEVEL = "Warn"
HYPOTH_LOG_LEVEL = "Warn"


[Tournament]
GAMES_PER_MAP = 10
MAPS_PER_EPOCH = 10
# Number of epochs (1 epoch is M*N games) to run
NUM_EPOCHS = 50

[PlayerSettings]
FEATURES = "./data/features.csv"
PUBLIC_FEATURES = "./data/public_features.csv"
MODELS_DIR = "./models"
MODEL = "linear_model.csv"
PUBLIC_MODEL = "public_linear_model.csv"
STATE_VALUES = "./data/state_values.csv"
REWARD_WEIGHT = 1.0
VALUE_WEIGHT = 0.0
REWARD_DISCOUNT = 0.4
LEARNING_RATE = 0.1
SEARCH_DEPTH = 1
MODIFY_REINFORCEMENT_WEIGHTS = false

[PlayerSettings.blue]
TYPE = "HybridPlayer"
[PlayerSettings.cyan]
TYPE = "HybridPlayer"
[PlayerSettings.green]
TYPE = "HybridPlayer"
[PlayerSettings.yellow]
TYPE = "HybridPlayer"
