SAVE_GAME_TO_FILE = false
SAVE_FILE = "savefile.txt"
LOG_OUTPUT = "stderr"
LOG_LEVEL = "Logging.Debug"
PRINT_BOARD = true
MAX_TURNS = 500
TEAMS = ["blue", "cyan", "green", "yellow"]

[Tournament]
GAMES_PER_MAP = 100
MAPS_PER_EPOCH = 2
# Number of epochs (1 epoch is M*N games) to run
NUM_EPOCHS = 1

[GameSettings]
[PlayerSettings]
MODEL = "../CatanLearning.jl/data/model.jls"
FEATURES = "../CatanLearning.jl/features.csv"
STATE_VALUES = "../CatanLearning.jl/state_values.csv"
[PlayerSettings.blue]
TYPE = "CatanLearning.EmpathRobotPlayer"
[PlayerSettings.cyan]
TYPE = "Catan.DefaultRobotPlayer"
[PlayerSettings.green]
TYPE = "Catan.DefaultRobotPlayer"
[PlayerSettings.yellow]
TYPE = "Catan.DefaultRobotPlayer"
