SAVE_GAME_TO_FILE = false
SAVE_FILE = "savefile.txt"
PRINT_BOARD = false
TEAMS = ["blue", "cyan", "green", "yellow"]
WRITE_FEATURES = true

[LogSettings]
LOG_OUTPUT = ""
LOG_LEVEL = "Info"

[Tournament]
GAMES_PER_MAP = 50
MAPS_PER_EPOCH = 50
# Number of epochs (1 epoch is M*N games) to run
NUM_EPOCHS = 1

[GameSettings]
[PlayerSettings]
MODEL = "../CatanLearning.jl/data/model.jls"
PUBLIC_MODEL = "../CatanLearning.jl/data/public_model.jls"
FEATURES = "./data/features.csv"
PUBLIC_FEATURES = "./data/public_features.csv"
[PlayerSettings.blue]
TYPE = "DefaultRobotPlayer"
[PlayerSettings.cyan]
TYPE = "DefaultRobotPlayer"
[PlayerSettings.green]
TYPE = "DefaultRobotPlayer"
[PlayerSettings.yellow]
TYPE = "DefaultRobotPlayer"
