SAVE_GAME_TO_FILE = false
SAVE_FILE = "savefile.txt"
#LOG_OUTPUT = ""
LOG_OUTPUT = "stderr"
LOG_LEVEL = "Info"
PRINT_BOARD = false
TEAMS = ["blue", "cyan", "green", "yellow"]
WRITE_FEATURES = false
MAX_TURNS = 500

[LogSettings]
GAME_LOG_LEVEL = "Warn"
HYPOTH_LOG_LEVEL = "Warn"

[Tournament]
GAMES_PER_MAP = 10
MAPS_PER_EPOCH = 20
# Number of epochs (1 epoch is M*N games) to run
NUM_EPOCHS = 1

[GameSettings]
[GameSettings.DevCards]
#KNIGHT = 0
#ROAD_BUILDING = 0
#YEAR_OF_PLENTY = 20
#MONOPOLY = 0
#VICTORY_POINT = 0

[PlayerSettings]
MODEL = "../CatanLearning.jl/models/model.jls"
#MODEL = "../CatanLearning.jl/models/linear_model.csv"
PUBLIC_MODEL = "../CatanLearning.jl/models/public_model.jls"
FEATURES = "./data/features.csv"
PUBLIC_FEATURES = "./data/public_features.csv"
[PlayerSettings.blue]
TYPE = "EmpathRobotPlayer"
SEARCH_DEPTH = 3
[PlayerSettings.cyan]
TYPE = "EmpathRobotPlayer"
SEARCH_DEPTH = 2
MODEL = "../CatanLearning.jl/models/linear_model.csv"
[PlayerSettings.green]
REWARD_WEIGHT = 0.4
VALUE_WEIGHT = 0.6
REWARD_DISCOUNT = 0.5
LEARNING_RATE = 0.1
SEARCH_DEPTH = 1
MODEL = "../CatanLearning.jl/models/linear_model.csv"
TYPE = "HybridPlayer"
[PlayerSettings.yellow]
TYPE = "DefaultRobotPlayer"
