SAVE_GAME_TO_FILE = false
SAVE_FILE = "savefile.txt"
LOG_OUTPUT = "./tmp/validate_log.txt"
#LOG_OUTPUT = "stderr"
#LOG_LEVEL = "Logging.Info"
LOG_LEVEL = "Logging.Debug"
PRINT_BOARD = true
MAX_TURNS = 500
TEAMS = ["blue", "cyan", "green", "yellow"]

[Tournament]
GAMES_PER_MAP = 1
MAPS_PER_EPOCH = 1
# Number of epochs (1 epoch is M*N games) to run
NUM_EPOCHS = 1

[GameSettings]
[PlayerSettings]
MODEL = "../CatanLearning.jl/data/model.jls"
PUBLIC_MODEL = "../CatanLearning.jl/data/naive_public_model.jls"
FEATURES = "../CatanLearning.jl/features.csv"
STATE_VALUES = "../CatanLearning.jl/state_values.csv"
SEARCH_DEPTH = 2
[PlayerSettings.blue]
TYPE = "EmpathRobotPlayer"
[PlayerSettings.cyan]
TYPE = "DefaultRobotPlayer"
[PlayerSettings.green]
TYPE = "DefaultRobotPlayer"
[PlayerSettings.yellow]
TYPE = "DefaultRobotPlayer"
