DATA_DIR = "."
SAVE_GAME_TO_FILE = false
SAVE_FILE = "savefile.txt"
LOG_OUTPUT = ""
LOG_LEVEL = "Logging.Info"
PRINT_BOARD = false
MAX_TURNS = 1000
TEAMS = ["blue", "cyan", "green", "yellow"]

[Tournament]
GAMES_PER_MAP = 100
MAPS_PER_EPOCH = 100
# Number of epochs (1 epoch is M*N games) to run
NUM_EPOCHS = 10

[GameSettings]
[PlayerSettings]
MODEL = "../CatanLearning.jl/data/model.jls"
PUBLIC_MODEL = "../CatanLearning.jl/data/public_model.jls"
# Features used in the main board state WonGame binary classification model
FEATURES = "./data/features.csv"
# Features used in the model that only relies on public information of the board and player state
PUBLIC_FEATURES = "./data/public_features.csv"
STATE_VALUES = "../CatanLearning.jl/state_values.csv"
[PlayerSettings.blue]
TYPE = "DefaultRobotPlayer"
[PlayerSettings.cyan]
TYPE = "DefaultRobotPlayer"
[PlayerSettings.green]
TYPE = "DefaultRobotPlayer"
[PlayerSettings.yellow]
TYPE = "DefaultRobotPlayer"
