SAVE_GAME_TO_FILE = false
SAVE_FILE = ""
LOAD_MAP = "canonical_map.csv"
SAVE_MAP = "canonical_map.csv"
PRINT_BOARD = false
TEAMS = ["blue", "cyan", "green", "red"]
WRITE_FEATURES = false
WRITE_VALUES = false
MAX_TURNS = 500
SERIALIZATION_STRATEGY = "JSON"

[LogSettings]
LOG_OUTPUT = "stderr"
#LOG_LEVEL = "Debug"
LOG_LEVEL = "Info"
GAME_LOG_LEVEL = "Warn"
HYPOTH_LOG_LEVEL = "Warn"

[Tournament]
GAMES_PER_MAP = 100
MAPS_PER_EPOCH = 10
NUM_EPOCHS = 1
GENERATE_RANDOM_MAPS = false

[PlayerSettings]
MODEL = "model.csv"
PUBLIC_MODEL = "public_model.csv"
FEATURES = "./canonical_features.csv"
PUBLIC_FEATURES = "./canonical_public_features.csv"
MODELS_DIR = "./models"
STATE_VALUES = "./state_values.csv"
REWARD_WEIGHT = 0.0
VALUE_WEIGHT = 1.0
REWARD_DISCOUNT = 0.4
LEARNING_RATE = 0.1
SEARCH_DEPTH = 1
MODIFY_REINFORCEMENT_WEIGHTS = true
[PlayerSettings.blue]
TYPE = "HybridPlayer"
[PlayerSettings.cyan]
TYPE = "DefaultRobotPlayer"
[PlayerSettings.green]
TYPE = "DefaultRobotPlayer"
[PlayerSettings.red]
TYPE = "DefaultRobotPlayer"
